# Generated by Django 4.2.1 on 2023-06-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "projects",
            "0002_remove_project_created_at_remove_project_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects", verbose_name="Imagem"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
