# Generated by Django 4.2.1 on 2023-06-02 00:42
from django.db import migrations, transaction
from django.contrib.auth.models import Group, Permission


def fix_perms(*app_labels):
    def wrapped(apps, schema_editor):
        from django.apps.registry import apps
        from django.contrib.auth.management import create_permissions

        for app in app_labels:
            app_conf = apps.get_app_config(app)
            create_permissions(app_conf, interactive=False)

    return wrapped


def add_groups(apps, schema_editor):
    reader_group = Group.objects.create(name="Reader")
    editor_group = Group.objects.create(name="Editor")

    with transaction.atomic():
        reader_group.permissions.set([Permission.objects.get(codename="view_project")])
        editor_group.permissions.set(
            [
                Permission.objects.get(codename="view_project"),
                Permission.objects.get(codename="add_project"),
                Permission.objects.get(codename="change_project"),
                Permission.objects.get(codename="delete_project"),
            ]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(fix_perms("projects")),
        migrations.RunPython(add_groups),
    ]
