# Generated by Django 4.2.1 on 2023-06-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_address_user_city_user_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Endereço"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cidade"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("user", "Usuário")],
                default="user",
                max_length=5,
                verbose_name="Perfil",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Estado"
            ),
        ),
    ]
